# Generated by Django 2.0.8 on 2019-02-07 15:49

from django.db import migrations
import extendedsearch.index


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProxy',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=(extendedsearch.index.Indexed, 'catalogue.category'),
        ),
        migrations.CreateModel(
            name='ProductProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'managed': False,
                'proxy': True,
            },
            bases=('catalogue.product', extendedsearch.index.Indexed),
        ),
    ]
