# Generated by Django 2.2.13 on 2020-09-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_categoryproxy_productproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Synonym',
        ),
    ]
