name: django-oscar-elasticsearch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11']
        django-version: ['4.2']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pip install -e .[dev]
    - name: Run Elasticsearch
      uses: JonasGe/elasticsearch-with-plugins-action@0.1.4
      with:
        # The version of the Elastic Stack you want to run
        stack-version: '6.8.2'
    - name: Run linters
      run: make lint
    - name: Run Tests
      run: make test
